# Generated by Django 5.1.3 on 2024-11-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "todo", "verbose_name_plural": "todo_list"},
        ),
        migrations.AddField(
            model_name="todo",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
