# Generated by Django 5.1.3 on 2024-12-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_todo_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="is_complete",
            new_name="is_completed",
        ),
    ]
